[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[theme]
base="dark"
primaryColor="#d33682"
backgroundColor="#000000"
secondaryBackgroundColor="#586e75"
textColor="#fafafa"
font="sans serif"